//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Final.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Main_Form_Location {
            get {
                return ((global::System.Drawing.Point)(this["Main_Form_Location"]));
            }
            set {
                this["Main_Form_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Player_Form_Location {
            get {
                return ((global::System.Drawing.Point)(this["Player_Form_Location"]));
            }
            set {
                this["Player_Form_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Team_Form_Location {
            get {
                return ((global::System.Drawing.Point)(this["Team_Form_Location"]));
            }
            set {
                this["Team_Form_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string DGV_Column_Width {
            get {
                return ((string)(this["DGV_Column_Width"]));
            }
            set {
                this["DGV_Column_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public global::System.Drawing.Color EvenRowColor {
            get {
                return ((global::System.Drawing.Color)(this["EvenRowColor"]));
            }
            set {
                this["EvenRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color OddRowColor {
            get {
                return ((global::System.Drawing.Color)(this["OddRowColor"]));
            }
            set {
                this["OddRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DGV_Row_Headers_Width {
            get {
                return ((int)(this["DGV_Row_Headers_Width"]));
            }
            set {
                this["DGV_Row_Headers_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200, 700")]
        public global::System.Drawing.Size Main_Form_Size {
            get {
                return ((global::System.Drawing.Size)(this["Main_Form_Size"]));
            }
            set {
                this["Main_Form_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt")]
        public global::System.Drawing.Font DGV_Font {
            get {
                return ((global::System.Drawing.Font)(this["DGV_Font"]));
            }
            set {
                this["DGV_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200, 700")]
        public global::System.Drawing.Size Team_Form_Size {
            get {
                return ((global::System.Drawing.Size)(this["Team_Form_Size"]));
            }
            set {
                this["Team_Form_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string DGV_Players_Column_Width {
            get {
                return ((string)(this["DGV_Players_Column_Width"]));
            }
            set {
                this["DGV_Players_Column_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DGV_Players_Row_Headers_Width {
            get {
                return ((int)(this["DGV_Players_Row_Headers_Width"]));
            }
            set {
                this["DGV_Players_Row_Headers_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font Setting {
            get {
                return ((global::System.Drawing.Font)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public float DGV_Font_Size {
            get {
                return ((float)(this["DGV_Font_Size"]));
            }
            set {
                this["DGV_Font_Size"] = value;
            }
        }
    }
}
