//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Final.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Main_Form_Location {
            get {
                return ((global::System.Drawing.Point)(this["Main_Form_Location"]));
            }
            set {
                this["Main_Form_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Player_Form_Location {
            get {
                return ((global::System.Drawing.Point)(this["Player_Form_Location"]));
            }
            set {
                this["Player_Form_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Team_Form_Location {
            get {
                return ((global::System.Drawing.Point)(this["Team_Form_Location"]));
            }
            set {
                this["Team_Form_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string Main_DGV_Column_Width {
            get {
                return ((string)(this["Main_DGV_Column_Width"]));
            }
            set {
                this["Main_DGV_Column_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public global::System.Drawing.Color Main_EvenRowColor {
            get {
                return ((global::System.Drawing.Color)(this["Main_EvenRowColor"]));
            }
            set {
                this["Main_EvenRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color Main_OddRowColor {
            get {
                return ((global::System.Drawing.Color)(this["Main_OddRowColor"]));
            }
            set {
                this["Main_OddRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DGV_Row_Headers_Width {
            get {
                return ((int)(this["DGV_Row_Headers_Width"]));
            }
            set {
                this["DGV_Row_Headers_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200, 700")]
        public global::System.Drawing.Size Main_Form_Size {
            get {
                return ((global::System.Drawing.Size)(this["Main_Form_Size"]));
            }
            set {
                this["Main_Form_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt")]
        public global::System.Drawing.Font DGV_Font {
            get {
                return ((global::System.Drawing.Font)(this["DGV_Font"]));
            }
            set {
                this["DGV_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200, 700")]
        public global::System.Drawing.Size Team_Form_Size {
            get {
                return ((global::System.Drawing.Size)(this["Team_Form_Size"]));
            }
            set {
                this["Team_Form_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string DGV_Players_Column_Width {
            get {
                return ((string)(this["DGV_Players_Column_Width"]));
            }
            set {
                this["DGV_Players_Column_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int DGV_Players_Row_Headers_Width {
            get {
                return ((int)(this["DGV_Players_Row_Headers_Width"]));
            }
            set {
                this["DGV_Players_Row_Headers_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Match_Form_Location {
            get {
                return ((global::System.Drawing.Point)(this["Match_Form_Location"]));
            }
            set {
                this["Match_Form_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public global::System.Drawing.Color MatchHome_OddRowColor {
            get {
                return ((global::System.Drawing.Color)(this["MatchHome_OddRowColor"]));
            }
            set {
                this["MatchHome_OddRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color MatchHome_EvenRowColor {
            get {
                return ((global::System.Drawing.Color)(this["MatchHome_EvenRowColor"]));
            }
            set {
                this["MatchHome_EvenRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public global::System.Drawing.Color MatchVisitor_OddRowColor {
            get {
                return ((global::System.Drawing.Color)(this["MatchVisitor_OddRowColor"]));
            }
            set {
                this["MatchVisitor_OddRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color MatchVisitor_EvenRowColor {
            get {
                return ((global::System.Drawing.Color)(this["MatchVisitor_EvenRowColor"]));
            }
            set {
                this["MatchVisitor_EvenRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt")]
        public global::System.Drawing.Font MatchHome_Font {
            get {
                return ((global::System.Drawing.Font)(this["MatchHome_Font"]));
            }
            set {
                this["MatchHome_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt")]
        public global::System.Drawing.Font MatchVisitor_Font {
            get {
                return ((global::System.Drawing.Font)(this["MatchVisitor_Font"]));
            }
            set {
                this["MatchVisitor_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MatchOption_Location {
            get {
                return ((global::System.Drawing.Point)(this["MatchOption_Location"]));
            }
            set {
                this["MatchOption_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Main_DGV_ForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Main_DGV_ForeColor"]));
            }
            set {
                this["Main_DGV_ForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Match_Home_ForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Match_Home_ForeColor"]));
            }
            set {
                this["Match_Home_ForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Match_Visitor_ForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Match_Visitor_ForeColor"]));
            }
            set {
                this["Match_Visitor_ForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AddPlayer_Location {
            get {
                return ((global::System.Drawing.Point)(this["AddPlayer_Location"]));
            }
            set {
                this["AddPlayer_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AddMatch_Location {
            get {
                return ((global::System.Drawing.Point)(this["AddMatch_Location"]));
            }
            set {
                this["AddMatch_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AddDivision_Location {
            get {
                return ((global::System.Drawing.Point)(this["AddDivision_Location"]));
            }
            set {
                this["AddDivision_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainOption_Location {
            get {
                return ((global::System.Drawing.Point)(this["MainOption_Location"]));
            }
            set {
                this["MainOption_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point AddTeam_Location {
            get {
                return ((global::System.Drawing.Point)(this["AddTeam_Location"]));
            }
            set {
                this["AddTeam_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EditMatch_Location {
            get {
                return ((global::System.Drawing.Point)(this["EditMatch_Location"]));
            }
            set {
                this["EditMatch_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MatchHistoric_Location {
            get {
                return ((global::System.Drawing.Point)(this["MatchHistoric_Location"]));
            }
            set {
                this["MatchHistoric_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point PlayerForm_Location {
            get {
                return ((global::System.Drawing.Point)(this["PlayerForm_Location"]));
            }
            set {
                this["PlayerForm_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point Top5_Location {
            get {
                return ((global::System.Drawing.Point)(this["Top5_Location"]));
            }
            set {
                this["Top5_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt")]
        public global::System.Drawing.Font Team_Form_Font {
            get {
                return ((global::System.Drawing.Font)(this["Team_Form_Font"]));
            }
            set {
                this["Team_Form_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Team_Form_FontColor {
            get {
                return ((global::System.Drawing.Color)(this["Team_Form_FontColor"]));
            }
            set {
                this["Team_Form_FontColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 192")]
        public global::System.Drawing.Color Team_OddRowColor {
            get {
                return ((global::System.Drawing.Color)(this["Team_OddRowColor"]));
            }
            set {
                this["Team_OddRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 255")]
        public global::System.Drawing.Color Team_EvenRowColor {
            get {
                return ((global::System.Drawing.Color)(this["Team_EvenRowColor"]));
            }
            set {
                this["Team_EvenRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 192")]
        public global::System.Drawing.Color MatchHistoric_OddRowColor {
            get {
                return ((global::System.Drawing.Color)(this["MatchHistoric_OddRowColor"]));
            }
            set {
                this["MatchHistoric_OddRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 255")]
        public global::System.Drawing.Color MatchHistoric_EvenRowColor {
            get {
                return ((global::System.Drawing.Color)(this["MatchHistoric_EvenRowColor"]));
            }
            set {
                this["MatchHistoric_EvenRowColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 9.75pt")]
        public global::System.Drawing.Font MatchHistoric_Font {
            get {
                return ((global::System.Drawing.Font)(this["MatchHistoric_Font"]));
            }
            set {
                this["MatchHistoric_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MatchHistoric_FontColor {
            get {
                return ((global::System.Drawing.Color)(this["MatchHistoric_FontColor"]));
            }
            set {
                this["MatchHistoric_FontColor"] = value;
            }
        }
    }
}
